package cn.sijay.owl;


import org.jspecify.annotations.NonNull;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardOpenOption;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

/**
 * MainTest
 *
 * @author sijay
 * @since 2026-04-13
 */
public class MainTest {

    public static void main(String[] args) throws IOException {
        HashMap<String, String> map = getMap();
        map.get("");
        List<String> list = Files.readAllLines(new File("pomTmp.xml").toPath());
        ArrayList<String> newList = new ArrayList<>();
        for (String s : list) {
            for (String key : map.keySet()) {
                if (s.contains(key)) {
                    s = s.replace(key, map.get(key));
                }
            }
            newList.add(s);
        }
        Files.write(new File("pomTmp2.xml").toPath(), newList, StandardOpenOption.TRUNCATE_EXISTING, StandardOpenOption.CREATE);
    }

    private static @NonNull HashMap<String, String> getMap() {
        HashMap<String, String> map = new HashMap<>();
        map.put("pentaho-launcher.version", "11.1.0.0-SNAPSHOT");
        map.put("oss-licenses.version", "11.1.0.0-SNAPSHOT");
        map.put("pentaho-karaf.version", "11.1.0.0-SNAPSHOT");
        map.put("org.eclipse.swt.gtk.linux.x86.version", "3.108.0");
        map.put("org.eclipse.swt.gtk.linux.x86_64.version", "3.108.0");
        map.put("org.eclipse.swt.win32.win32.x86_64.version", "3.122.0");
        map.put("org.eclipse.swt.cocoa.macosx.x86_64.version", "3.115.100");
        map.put("org.eclipse.swt.cocoa.macosx.aarch64.version", "3.122.0");
        map.put("pdi-engine-spark.version", "11.1.0.0-SNAPSHOT");
        map.put("rxjava.version", "2.2.3");
        map.put("pentaho-mongodb-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("big-data-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("pentaho-json.version", "11.1.0.0-SNAPSHOT");
        map.put("pdi-spark-driver.version", "11.1.0.0-SNAPSHOT");
        map.put("commons-database.version", "11.1.0.0-SNAPSHOT");
        map.put("pentaho-registry.version", "11.1.0.0-SNAPSHOT");
        map.put("pentaho-metaverse.version", "11.1.0.0-SNAPSHOT");
        map.put("platform.version", "11.1.0.0-SNAPSHOT");
        map.put("pentaho-reporting.version", "11.1.0.0-SNAPSHOT");
        map.put("pdi-osgi-bridge.version", "11.1.0.0-SNAPSHOT");
        map.put("pentaho-hadoop-shims.version", "11.1.0.0-SNAPSHOT");
        map.put("hsqldb.version", "2.3.2");
        map.put("jaybird.version", "2.1.6");
        map.put("jt400.version", "6.1");
        map.put("LucidDbClient-minimal.version", "0.9.4");
        map.put("sapdbc.version", "7.4.4");
        map.put("asm.version", "3.2");
        map.put("blueprints-core.version", "2.6.0");
        map.put("commons-configuration.version", "1.9");
        map.put("flexjson.version", "2.1");
        map.put("mimepull.version", "1.9.3");
        map.put("enunciate-jersey-rt.version", "1.27");
        map.put("enunciate-core-annotations.version", "1.28");
        map.put("databricks.version", "4.0.0");
        map.put("jface.version", "3.3.0-I20070606-0010");
        map.put("pentaho-metadata.version", "11.1.0.0-SNAPSHOT");
        map.put("google-http-client.version", "1.42.3");
        map.put("pax-swissbox-core.version", "1.8.2");
        map.put("javax.activation.version", "1.1.1");
        map.put("pdi-core-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("kettle-s3csvinput-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("kettle-shapefilereader-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("kettle-drools8-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("kettle-gpload-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("kettle-hl7-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("mail-job-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("pdi-salesforce-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("monet-db-bulk-loader-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("yaml-input-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("pentaho-reporting-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("ms-access-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("get-file-sftp-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("ftps-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("oracle-bulk-loader-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("terafast-bulk-loader-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("postgresql-db-bulk-loader-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("rss-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("infobright-bulk-loader-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("excel-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("ldap-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("ivw-bulk-loader-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("sftpput-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("put-file-sftp-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("edi2xml-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("random-cc-number-generator-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("credit-card-validator-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("mondrianinput-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("pdi-sap-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("jms-streaming-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("pdi-teradata-tpt-plugin-package.version", "11.1.0.0-SNAPSHOT");
        map.put("pdi-platform-utils-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("vertica-bulkloader-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("pdi-pur-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("engine-configuration-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("metastore-locator-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("repository-locator-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("file-open-save-new-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("mysql-bulk-load-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("repositories-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("connections-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("meta-inject-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("mqtt-streaming-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("pentaho-s3-vfs-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("pdi-avro-format-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("mail-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("pdi-xml-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("pdi-json-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("pdi-rest-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("get-repository-names-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("connected-to-repository-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("export-repository-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("ftp-delete-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("mail-validator-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("email-messages-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("put-a-file-with-ftp-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("get-file-with-ftp.version", "11.1.0.0-SNAPSHOT");
        map.put("msg-box-info.version", "11.1.0.0-SNAPSHOT");
        map.put("repo-vfs.version", "11.1.0.0-SNAPSHOT");
        map.put("pentaho-streaming-kafka-plugin.version", "11.1.0.0-SNAPSHOT");
        map.put("properties-maven-plugin.version", "1.0.0");
        map.put("sql-maven-plugin.version", "1.5");
        map.put("encryption-support.version", "11.1.0.0-SNAPSHOT");
        map.put("maven-surefire-plugin.reuseForks", "true");
        map.put("maven-surefire-plugin.argLine", "-Duser.timezone=UTC -Dfile.encoding=UTF-8 -Duser.language=en -Duser.country=US -Djava.locale.providers=COMPAT,SPI");
        map.put("xml-apis-ext.version", "1.3.04");
        map.put("commons-collections.version", "3.2.2");
        map.put("commons-lang.version", "2.6");
        map.put("jug-lgpl.version", "2.0.0");
        map.put("ognl.version", "2.6.9");
        map.put("scannotation.version", "1.0.2");
        map.put("com.wcohen.secondstring.version", "0.1");
        map.put("javassist.version", "3.20.0-GA");
        map.put("jcifs.version", "1.3.3");
        map.put("xmlunit.version", "1.5");
        map.put("joda.version", "2.10.2");
        map.put("com.github.spotbugs.annotations.version", "4.2.3");
        map.put("jupiter.version", "5.10.2");
        map.put("powermock.version", "2.0.9");
        map.put("maven-failsafe-plugin.reuseForks", "false");
        map.put("pentaho-connections.version", "11.1.0.0-SNAPSHOT");
        map.put("mondrian.version", "11.1.0.0-SNAPSHOT");
        map.put("antlr-complete.version", "3.5.2");
        map.put("commons-validator.version", "1.3.1");
        map.put("edtftpj.version", "2.1.0");
        map.put("jsendnsca.version", "2.0.1");
        map.put("feed4j.version", "1.0");
        map.put("ftp4che.version", "0.7.1");
        map.put("infobright-core.version", "3.4");
        map.put("javadbf.version", "20081125");
        map.put("jcommon.version", "1.0.16");
        map.put("json-simple.version", "1.1");
        map.put("jsonpath.version", "1.0");
        map.put("jxl.version", "2.6.12");
        map.put("ldapjdk.version", "20000524");
        map.put("odfdom-java.version", "0.8.6");
        map.put("commons-collections4.version", "4.4");
        map.put("commons-math3.version", "3.6.1");
        map.put("curvesapi.version", "1.06");
        map.put("SassyReader.version", "0.5");
        map.put("snmp4j.version", "1.9.3d");
        map.put("syslog4j.version", "0.9.46");
        map.put("jaxrpc-api.version", "1.1");
        map.put("olap4j.version", "1.2.0");
        map.put("olap4j-xmla.version", "1.2.0");
        map.put("wsdl4j.version", "1.6.2");
        map.put("wsdl4j-qname.version", "1.6.1");
        map.put("hibernate-commons-annotations.version", "3.2.0.Final");
        map.put("jboss-logging.version", "3.4.3.Final");
        map.put("cglib-nodep.version", "2.2");
        map.put("js.version", "1.7R3");
        map.put("mstor.version", "0.9.13");
        map.put("commons-cli.version", "1.2");
        map.put("log4jdbc.version", "1.2");
        map.put("oro.version", "2.0.8");
        map.put("wiremock.version", "2.25.0");
        map.put("xmlbeans.version", "5.3.0");
        map.put("reactive-streams.version", "1.0.0");
        map.put("pdi-version", "11.1.0.0-SNAPSHOT");
        map.put("pdi.version", "11.1.0.0-SNAPSHOT");
        map.put("mockito-all.version", "1.9.5");
        map.put("project.revision", "11.1.0.0-SNAPSHOT");
        map.put("build.revision", "11.1.0.0-SNAPSHOT");
        map.put("timestamp", "${maven.build.timestamp}");
        map.put("build.description", "${project.description}");
        map.put("maven.build.timestamp.format", "yyyy-MM-dd hh.mm.ss");
        map.put("resources.directory", "${project.basedir}/src/main/resources");
        map.put("assembly.dir", "${project.build.directory}/assembly");
        map.put("tukaani-xz.version", "1.10");
        map.put("zstd-jni.version", "1.5.7-6");
        map.put("org.eclipse.swt.version", "4.6");
        map.put("dependency.karaf.version", "3.0.3");
        map.put("dependency.osgi.version", "4.3.1");
        map.put("version.for.license", "11.1.0.0-SNAPSHOT");
        map.put("pentaho-osgi-bundles.version", "11.1.0.0-SNAPSHOT");
        map.put("cxf.karaf.version", "3.0.13");
        map.put("swt.version", "4.6");
        map.put("maven-replacer-plugin.version", "1.5.2");
        map.put("samples.directory", "${project.basedir}/samples");
        map.put("drools.version", "8.44.0.Final");
        map.put("mvel2.version", "2.5.2.Final");
        map.put("org.eclipse.jdt", "3.4.2.v_883_R34x");
        map.put("junit.version", "4.12");
        map.put("elasticsearch.version", "6.4.2");
        map.put("mockito.version", "5.10.0");
        map.put("maven-bundle-plugin.version", "2.4.0");
        map.put("ftpserver-core.version", "1.0.6");
        map.put("encoder.version", "1.2");
        map.put("license.licenseName", "vantara");
        map.put("dependency.com.tinkerpop.blueprints.version", "2.6.0");
        map.put("dependency.org.powermock.version", "1.6.0");
        map.put("json-path.version", "2.5.0");
        map.put("minidev-asm.version", "1.0.2");
        map.put("publish-sonar-phase", "site");
        map.put("dependency.com.tinkerpop.frames.version", "2.5.0");
        map.put("osgi.version", "8.0.0");
        map.put("dependency.hamcrest.revision", "1.3");
        map.put("mockito-core.version", "5.17.0");
        map.put("hamcrest.version", "1.3");
        map.put("ascsapjco3wrp.version", "20100529");
        map.put("project.http.version", "1.42.3");
        map.put("project.oauth.version", "1.22.0");
        map.put("project.junit.version", "4.4");
        map.put("maven-failsafe-plugin.argLine", "--add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED");
        map.put("wadl-core.version", "1.1.6");
        map.put("wadl-ant.version", "1.1.6");
        map.put("se-jcr.version", "0.9");
        map.put("jcr.version", "2.0");
        map.put("derby.version", "10.17.1.0");
        map.put("wadl2java.generated-class-name", "Localhost_PentahoPlugin");
        map.put("wadl2java.desired-class-name", "PentahoDiPlugin");
        map.put("wadl2java.codedir", "src/main/java/com/pentaho/di/services");
        map.put("wadl2java.target-package", "com.pentaho.di.services");
        map.put("metastore.version", "11.1.0.0-SNAPSHOT");
        map.put("pentaho-platform.version", "${pdi.version}");
        map.put("junit-jupiter.version", "5.13.0-M2");
        map.put("maven-surefire-plugin.version", "3.2.5");
        map.put("eclipse.version", "3.6.0");
        map.put("commons-xul.version", "11.1.0.0-SNAPSHOT");
        map.put("argLine", "--add-opens=java.base/java.lang=ALL-UNNAMED");
        map.put("slf4j-api.version", "1.7.7");
        map.put("com.force.api.version", "54.0.0");
        map.put("ibmmq.version", "9.4.0.0");
        map.put("jms.version", "2.0.1");
        map.put("artemis.version", "2.33.0");
        map.put("pentaho-metastore.version", "11.1.0.0-SNAPSHOT");
        map.put("jsch.version", "0.2.9");
        map.put("monetdb-jdbc.version", "2.8");
        map.put("commons-configuration2.version", "2.10.1");
        map.put("powermock-module-junit4.version", "1.7.3");
        map.put("powermock-api-mockito.version", "1.7.3");
        map.put("java-hamcrest.version", "2.0.0.0");
        map.put("pentaho-vfs-browser.version", "11.1.0.0-SNAPSHOT");
        map.put("pentaho-capability-manager.version", "11.1.0.0-SNAPSHOT");
        map.put("common.version", "3.3.0-v20070426");
        map.put("commands.version", "3.3.0-I20070605-0010");
        map.put("jfreechart.version", "1.0.13");
        return map;
    }
}
