spring:
    application:
        name: owl
        version: 0.0.1
    profiles:
        active: dev
    mvc:
        static-path-pattern: /static/**
        format:
            date-time: yyyy-MM-dd HH:mm:ss
    jackson:
        deserialization:
            fail-on-unknown-properties: false
        serialization:
            fail-on-empty-beans: false
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    freemarker:
        template-loader-path: classpath:/templates/
        charset: UTF-8
        cache: false
    cache:
        type: redis
    threads:
        virtual:
            enabled: true
    task:
        execution:
            thread-name-prefix: async-
            mode: force

mybatis-flex:
    global-config:
        logic-delete-column: deleted
        deleted-value-of-logic-delete: true
        normal-value-of-logic-delete: false
        print-banner: false
        key-config:
            key-type: auto
    mapper-locations: classpath*:/mapper/**/*Mapper.xml

gen:
    #作者
    author: sijay
    #包路径
    package-name: cn.sijay.owl

