server:
    port: 9527
    servlet:
        context-path: /

spring:
    main:
        banner-mode: off
    datasource:
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        url: jdbc:p6spy:h2:file:./tmp/owl;DB_CLOSE_DELAY=-1;MODE=MySQL;AUTO_SERVER=TRUE
        username: sa
        password:
        hikari:
            maximum-pool-size: 5
            minimum-idle: 1
            idle-timeout: 30000
            max-lifetime: 120000
            auto-commit: true
            pool-name: HikariCP
            keepalive-time: 60000
    sql:
        init:
            mode: never
    h2:
        console:
            enabled: true
            path: /h2-console
    servlet:
        multipart:
            max-file-size: 50MB
            max-request-size: 50MB
    data:
        redis:
            host: localhost
            port: 6379
            password: 123456
            database: 6

logging:
    charset:
        console: utf-8
    pattern:
        console: '%red(%d{HH:mm:ss}) %green([%thread]) %highlight(%-5level) %boldMagenta(%logger%n) - %msg%n'
    level:
        root: info

sa-token:
    is-read-cookie: false
    token-style: simple-uuid
    token-prefix: 'Bearer'
    token-name: Authorization
    is-concurrent: true
    is-share: false
    is-print: false
    active-timeout: -1
    timeout: -1
