server:
    port: 9528
    servlet:
        context-path: /

spring:
    main:
        banner-mode: off
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/owl
        username: root
        password: root
        hikari:
            maximum-pool-size: 20
            minimum-idle: 10
            idle-timeout: 30000
            max-lifetime: 120000
            keepalive-time: 30000
            connection-timeout: 30000
            connection-test-query: SELECT 1
            auto-commit: true
            pool-name: HikariCP
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 20MB
    data:
        redis:
            host: localhost
            port: 6379
            password: 123456
            database: 2

logging:
    charset:
        console: utf-8
    pattern:
        console: '%red(%d{HH:mm:ss}) %green([%thread]) %highlight(%-5level) %boldMagenta(%logger%n) - %msg%n'
    level:
        root: info

decorator:
    datasource:
        p6spy:
            log-format: '%(sqlSingleLine)'

springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        enabled: true
    disable-i18n: false
    pre-loading-locales: CN
    paths-to-exclude:
        - /actuator/**

sa-token:
    is-read-cookie: false
    token-style: simple-uuid
    token-prefix: 'Bearer'
    token-name: Authorization
    is-concurrent: true
    is-share: false
    is-print: false
    active-timeout: -1
    timeout: -1
