INSERT INTO sys_user (id, dept_id, username, real_name, email, phone, gender, avatar, password, mfa_enabled, totp_secret, enabled, deleted, create_dept, create_by, create_time,
                      update_by, update_time)
VALUES (1, 0, 'admin', '管理员', '', '', 'UNKNOWN', null, '$2b$12$RaBkMzfs5s7kWWaOxO4vLu6bf6HCkL8.s9U76B1wCuyym6YT2lxqq', 0, null, 1, 0, 1, 1, '2026-05-26 18:25:09', 1,
        '2026-05-26 18:25:09');

INSERT INTO GEN_TABLE (TABLE_NAME, TABLE_COMMENT, MODULE_NAME, CLASS_NAME, CLASS_COMMENT, FUNCTION_NAME, TREE_TABLE, TREE_KEY, TREE_PARENT_KEY, TREE_LABEL, MENU_ID,
                       ENTITY_ONLY)
VALUES ('sys_config', '参数配置表', 'system', 'SysConfig', '参数配置', 'sysConfig', false, '', '', '', 1, false),
       ('sys_dept', '系统部门表', 'system', 'SysDept', '系统部门', 'sysDept', true, 'id', 'parent_id', 'dept_name', 1, false),
       ('sys_menu', '系统菜单表', 'system', 'SysMenu', '系统菜单', 'sysMenu', true, 'id', 'parent_id', 'menu_name', 1, false),
       ('sys_role', '系统角色表', 'system', 'SysRole', '系统角色', 'sysRole', false, '', '', '', 1, false),
       ('sys_role_menu', '角色菜单关联表', 'system', 'SysRoleMenu', '角色菜单关联', 'sysRoleMenu', false, '', '', '', 1, true),
       ('sys_user', '系统用户表', 'system', 'SysUser', '系统用户', 'sysUser', false, '', '', '', 1, false),
       ('sys_user_role', '用户角色关联表', 'system', 'SysUserRole', '用户角色关联', 'sysUserRole', false, '', '', '', 1, true);
INSERT INTO GEN_COLUMN (TABLE_ID, COLUMN_NAME, COLUMN_COMMENT, COLUMN_TYPE, JAVA_TYPE, JAVA_FIELD, MAX_LENGTH, PRIMARY_KEY, INCREMENTAL, REQUIRED, EDITABLE, LISTABLE,
                        QUERYABLE, QUERY_TYPE, HTML_TYPE, DICT_TYPE, SORT)
VALUES (1, 'id', '主键', 'bigint', 'LONG', 'id', null, true, true, true, true, true, false, 'EQUALS', 'SELECT', '', 1),
       (1, 'config_key', '参数键名', 'varchar', 'STRING', 'configKey', 100, false, false, false, true, true, true, 'LIKE', 'INPUT', '', 3),
       (1, 'config_value', '参数键值', 'varchar', 'STRING', 'configValue', 500, false, false, false, true, true, false, 'LIKE', 'TEXTAREA', '', 4),
       (1, 'create_dept', '创建部门', 'bigint', 'LONG', 'createDept', null, false, false, false, false, false, false, 'EQUALS', 'NUMBER', '', 5),
       (1, 'create_by', '创建者', 'bigint', 'LONG', 'createBy', null, false, false, false, false, false, false, 'EQUALS', 'NUMBER', '', 6),
       (1, 'create_time', '创建时间', 'timestamp', 'LOCAL_DATE_TIME', 'createTime', null, false, false, false, false, false, false, 'BETWEEN', 'DATETIME', '', 7),
       (1, 'update_by', '更新者', 'bigint', 'LONG', 'updateBy', null, false, false, false, false, false, false, 'EQUALS', 'NUMBER', '', 8),
       (1, 'update_time', '更新时间', 'timestamp', 'LOCAL_DATE_TIME', 'updateTime', null, false, false, false, false, false, false, 'BETWEEN', 'DATETIME', '', 9),
       (1, 'config_name', '参数名称', 'varchar', 'STRING', 'configName', 100, false, false, false, true, true, true, 'LIKE', 'INPUT', '', 2),
       (2, 'id', '主键', 'bigint', 'LONG', 'id', null, true, true, true, true, true, false, 'EQUALS', 'SELECT', '', 1),
       (2, 'parent_id', '父部门id', 'bigint', 'LONG', 'parentId', null, false, false, false, true, true, true, 'EQUALS', 'SELECT', '', 2),
       (2, 'ancestors', '祖级列表', 'varchar', 'STRING', 'ancestors', 1000, false, false, false, true, false, false, 'LIKE', 'TEXTAREA', '', 3),
       (2, 'dept_name', '部门名称', 'varchar', 'STRING', 'deptName', 30, false, false, false, true, true, true, 'LIKE', 'INPUT', '', 4),
       (2, 'dept_category', '部门类别', 'bigint', 'LONG', 'deptCategory', null, false, false, false, true, true, true, 'EQUALS', 'NUMBER', '', 5),
       (2, 'sort', '显示顺序', 'integer', 'INTEGER', 'sort', null, false, false, false, true, true, false, 'EQUALS', 'NUMBER', '', 6),
       (2, 'leader', '负责人', 'bigint', 'LONG', 'leader', null, false, false, false, true, true, false, 'EQUALS', 'NUMBER', '', 7),
       (2, 'phone', '联系电话', 'varchar', 'STRING', 'phone', 11, false, false, false, true, true, false, 'LIKE', 'INPUT', '', 8),
       (2, 'email', '邮箱', 'varchar', 'STRING', 'email', 50, false, false, false, true, true, false, 'LIKE', 'INPUT', '', 9),
       (2, 'enabled', '启用', 'boolean', 'BOOLEAN', 'enabled', null, false, false, false, true, true, true, 'EQUALS', 'RADIO', '', 10),
       (2, 'deleted', '删除', 'boolean', 'BOOLEAN', 'deleted', null, false, false, false, false, false, false, 'EQUALS', 'RADIO', '', 11),
       (2, 'create_dept', '创建部门', 'bigint', 'LONG', 'createDept', null, false, false, false, false, false, false, 'EQUALS', 'NUMBER', '', 12),
       (2, 'create_by', '创建者', 'bigint', 'LONG', 'createBy', null, false, false, false, false, false, false, 'EQUALS', 'NUMBER', '', 13),
       (2, 'create_time', '创建时间', 'timestamp', 'LOCAL_DATE_TIME', 'createTime', null, false, false, false, false, false, false, 'BETWEEN', 'DATETIME', '', 14),
       (2, 'update_by', '更新者', 'bigint', 'LONG', 'updateBy', null, false, false, false, false, false, false, 'EQUALS', 'NUMBER', '', 15),
       (2, 'update_time', '更新时间', 'timestamp', 'LOCAL_DATE_TIME', 'updateTime', null, false, false, false, false, false, false, 'BETWEEN', 'DATETIME', '', 16),
       (3, 'id', '主键', 'bigint', 'LONG', 'id', null, true, true, true, true, true, false, 'EQUALS', 'SELECT', '', 1),
       (3, 'menu_name', '菜单名称', 'varchar', 'STRING', 'menuName', 50, false, false, true, true, true, true, 'LIKE', 'INPUT', '', 2),
       (3, 'parent_id', '父菜单id', 'bigint', 'LONG', 'parentId', null, false, false, false, true, true, false, 'EQUALS', 'SELECT', '', 3),
       (3, 'sort', '显示顺序', 'integer', 'INTEGER', 'sort', null, false, false, false, true, true, false, 'EQUALS', 'NUMBER', '', 4),
       (3, 'path', '路由地址', 'varchar', 'STRING', 'path', 200, false, false, false, true, true, false, 'LIKE', 'INPUT', '', 5),
       (3, 'component', '组件路径', 'varchar', 'STRING', 'component', 255, false, false, false, true, true, false, 'LIKE', 'INPUT', '', 6),
       (3, 'query_param', '路由参数', 'varchar', 'STRING', 'queryParam', 255, false, false, false, true, true, false, 'LIKE', 'INPUT', '', 7),
       (3, 'foreign_link', '是否为外链', 'boolean', 'BOOLEAN', 'foreignLink', null, false, false, false, true, true, false, 'EQUALS', 'RADIO', '', 8),
       (3, 'cached', '是否缓存', 'boolean', 'BOOLEAN', 'cached', null, false, false, false, true, true, false, 'EQUALS', 'RADIO', '', 9),
       (3, 'menu_type', '菜单类型', 'varchar', 'STRING', 'menuType', 10, false, false, false, true, true, false, 'LIKE', 'INPUT', '', 10),
       (3, 'visible', '显示', 'boolean', 'BOOLEAN', 'visible', null, false, false, false, true, true, false, 'EQUALS', 'RADIO', '', 11),
       (3, 'enabled', '启用', 'boolean', 'BOOLEAN', 'enabled', null, false, false, false, true, true, true, 'EQUALS', 'RADIO', '', 12),
       (3, 'perms', '权限标识', 'varchar', 'STRING', 'perms', 100, false, false, false, true, true, false, 'LIKE', 'INPUT', '', 13),
       (3, 'icon', '菜单图标', 'varchar', 'STRING', 'icon', 100, false, false, false, true, true, false, 'LIKE', 'INPUT', '', 14),
       (3, 'active_menu', '高亮菜单', 'varchar', 'STRING', 'activeMenu', 100, false, false, false, true, true, false, 'LIKE', 'INPUT', '', 15),
       (3, 'create_dept', '创建部门', 'bigint', 'LONG', 'createDept', null, false, false, false, false, false, false, 'EQUALS', 'NUMBER', '', 16),
       (3, 'create_by', '创建者', 'bigint', 'LONG', 'createBy', null, false, false, false, false, false, false, 'EQUALS', 'NUMBER', '', 17),
       (3, 'create_time', '创建时间', 'timestamp', 'LOCAL_DATE_TIME', 'createTime', null, false, false, false, false, false, false, 'BETWEEN', 'DATETIME', '', 18),
       (3, 'update_by', '更新者', 'bigint', 'LONG', 'updateBy', null, false, false, false, false, false, false, 'EQUALS', 'NUMBER', '', 19),
       (3, 'update_time', '更新时间', 'timestamp', 'LOCAL_DATE_TIME', 'updateTime', null, false, false, false, false, false, false, 'BETWEEN', 'DATETIME', '', 20),
       (4, 'id', '主键', 'bigint', 'LONG', 'id', null, true, true, true, true, true, false, 'EQUALS', 'SELECT', '', 1),
       (4, 'role_name', '角色名称', 'varchar', 'STRING', 'roleName', 30, false, false, true, true, true, true, 'LIKE', 'INPUT', '', 2),
       (4, 'role_code', '角色权限字符串', 'varchar', 'STRING', 'roleCode', 100, false, false, true, true, true, false, 'LIKE', 'INPUT', '', 3),
       (4, 'sort', '显示顺序', 'integer', 'INTEGER', 'sort', null, false, false, true, true, true, false, 'EQUALS', 'NUMBER', '', 4),
       (4, 'data_scope', '数据权限', 'other', 'STRING', 'dataScope', 14, false, false, false, true, true, false, 'LIKE', 'INPUT', '', 5),
       (4, 'menu_check_strictly', '菜单树选择项关联显示', 'boolean', 'BOOLEAN', 'menuCheckStrictly', null, false, false, false, true, true, false, 'EQUALS', 'RADIO', '', 6),
       (4, 'dept_check_strictly', '部门树选择项关联显示', 'boolean', 'BOOLEAN', 'deptCheckStrictly', null, false, false, false, true, true, false, 'EQUALS', 'RADIO', '', 7),
       (4, 'enabled', '启用', 'boolean', 'BOOLEAN', 'enabled', null, false, false, false, true, true, true, 'EQUALS', 'RADIO', '', 8),
       (4, 'deleted', '删除', 'boolean', 'BOOLEAN', 'deleted', null, false, false, false, false, false, false, 'EQUALS', 'RADIO', '', 9),
       (4, 'create_dept', '创建部门', 'bigint', 'LONG', 'createDept', null, false, false, false, false, false, false, 'EQUALS', 'NUMBER', '', 10),
       (4, 'create_by', '创建者', 'bigint', 'LONG', 'createBy', null, false, false, false, false, false, false, 'EQUALS', 'NUMBER', '', 11),
       (4, 'create_time', '创建时间', 'timestamp', 'LOCAL_DATE_TIME', 'createTime', null, false, false, false, false, false, false, 'BETWEEN', 'DATETIME', '', 12),
       (4, 'update_by', '更新者', 'bigint', 'LONG', 'updateBy', null, false, false, false, false, false, false, 'EQUALS', 'NUMBER', '', 13),
       (4, 'update_time', '更新时间', 'timestamp', 'LOCAL_DATE_TIME', 'updateTime', null, false, false, false, false, false, false, 'BETWEEN', 'DATETIME', '', 14),
       (5, 'role_id', '角色id', 'bigint', 'LONG', 'roleId', null, true, false, true, true, true, false, 'EQUALS', 'SELECT', '', 1),
       (5, 'menu_id', '菜单id', 'bigint', 'LONG', 'menuId', null, true, false, true, true, true, false, 'EQUALS', 'SELECT', '', 2),
       (6, 'id', '主键', 'bigint', 'LONG', 'id', null, true, true, true, true, true, false, 'EQUALS', 'SELECT', '', 1),
       (6, 'dept_id', '部门id', 'bigint', 'LONG', 'deptId', null, false, false, false, true, true, true, 'EQUALS', 'SELECT', '', 2),
       (6, 'username', '用户账号', 'varchar', 'STRING', 'username', 20, false, false, true, true, true, true, 'LIKE', 'INPUT', '', 3),
       (6, 'real_name', '用户姓名', 'varchar', 'STRING', 'realName', 30, false, false, false, true, true, true, 'LIKE', 'INPUT', '', 4),
       (6, 'email', '邮箱', 'varchar', 'STRING', 'email', 50, false, false, false, true, true, true, 'LIKE', 'INPUT', '', 5),
       (6, 'phone', '手机号', 'varchar', 'STRING', 'phone', 11, false, false, false, true, true, true, 'LIKE', 'INPUT', '', 6),
       (6, 'gender', '性别', 'varchar', 'STRING', 'gender', 8, false, false, false, true, true, false, 'LIKE', 'INPUT', '', 7),
       (6, 'avatar', '头像', 'blob', 'BYTE_ARRAY', 'avatar', null, false, false, false, true, true, false, 'EQUALS', 'FILE', '', 8),
       (6, 'password', '密码', 'varchar', 'STRING', 'password', 100, false, false, true, false, false, false, 'LIKE', 'INPUT', '', 9),
       (6, 'mfa_enabled', '是否启用MFA', 'boolean', 'BOOLEAN', 'mfaEnabled', null, false, false, false, true, true, false, 'EQUALS', 'RADIO', '', 10),
       (6, 'totp_secret', 'TOTP密钥', 'varchar', 'STRING', 'totpSecret', 255, false, false, false, false, false, false, 'LIKE', 'INPUT', '', 11),
       (6, 'enabled', '启用', 'boolean', 'BOOLEAN', 'enabled', null, false, false, false, true, true, true, 'EQUALS', 'RADIO', '', 12),
       (6, 'deleted', '删除', 'boolean', 'BOOLEAN', 'deleted', null, false, false, false, false, false, false, 'EQUALS', 'RADIO', '', 13),
       (6, 'create_dept', '创建部门', 'bigint', 'LONG', 'createDept', null, false, false, false, false, false, false, 'EQUALS', 'NUMBER', '', 14),
       (6, 'create_by', '创建者', 'bigint', 'LONG', 'createBy', null, false, false, false, false, false, false, 'EQUALS', 'NUMBER', '', 15),
       (6, 'create_time', '创建时间', 'timestamp', 'LOCAL_DATE_TIME', 'createTime', null, false, false, false, false, false, false, 'BETWEEN', 'DATETIME', '', 16),
       (6, 'update_by', '更新者', 'bigint', 'LONG', 'updateBy', null, false, false, false, false, false, false, 'EQUALS', 'NUMBER', '', 17),
       (6, 'update_time', '更新时间', 'timestamp', 'LOCAL_DATE_TIME', 'updateTime', null, false, false, false, false, false, false, 'BETWEEN', 'DATETIME', '', 18),
       (7, 'user_id', '用户id', 'bigint', 'LONG', 'userId', null, true, false, true, true, true, false, 'EQUALS', 'SELECT', '', 1),
       (7, 'role_id', '角色id', 'bigint', 'LONG', 'roleId', null, true, false, true, true, true, false, 'EQUALS', 'SELECT', '', 2);
insert into sys_menu (ID, MENU_NAME, PARENT_ID, SORT, PATH, COMPONENT, QUERY_PARAM, FOREIGN_LINK, CACHED, MENU_TYPE, VISIBLE, ENABLED, PERMS, ICON, ACTIVE_MENU)
values (1, '系统管理', 0, 1, 'system', null, null, false, true, 'DIRECTORY', true, true, null, 'Menu', ''),
       (2, '系统工具', 0, 4, 'tool', null, null, false, true, 'DIRECTORY', true, true, '', 'Menu', ''),
       (3, '测试目录', 0, 100, 'testMenu', null, null, false, true, 'DIRECTORY', true, true, null, 'Menu', ''),
       (4, '配置管理', 1, 1, 'sys-config', '/system/sys-config', null, false, true, 'MENU', true, true, 'system:sysConfig:query', 'Menu', ''),
       (5, '部门管理', 1, 2, 'sys-dept', '/system/sys-dept', null, false, true, 'MENU', true, true, 'system:SysDept:query', 'Menu', ''),
       (6, '菜单管理', 1, 3, 'sys-menu', '/system/sys-menu', null, false, true, 'MENU', true, true, 'system:SysMenu:query', 'Menu', ''),
       (7, '角色管理', 1, 4, 'sys-role', '/system/sys-role', null, false, true, 'MENU', true, true, 'system:SysRole:query', 'Menu', ''),
       (8, '用户管理', 1, 5, 'sys-user', '/system/sys-user', null, false, true, 'MENU', true, true, 'system:SysUser:query', 'Menu', ''),
       (9, 'bing', 1, 9, 'https://bing.com', null, null, true, true, 'DIRECTORY', true, true, '', 'Menu', ''),
       (10, '配置管理-新增', 4, 1, '', null, null, false, true, 'BUTTON', true, true, 'system:sysConfig:save', '', ''),
       (11, '配置管理-修改', 4, 2, '', null, null, false, true, 'BUTTON', true, true, 'system:sysConfig:save', '', ''),
       (12, '配置管理-删除', 4, 3, '', null, null, false, true, 'BUTTON', true, true, 'system:sysConfig:delete', '', ''),
       (13, '配置管理-导入', 4, 4, '', null, null, false, true, 'BUTTON', true, true, 'system:sysConfig:import', '', ''),
       (14, '配置管理-导出', 4, 5, '', null, null, false, true, 'BUTTON', true, true, 'system:sysConfig:export', '', ''),
       (15, '部门管理-导出', 5, 5, '', null, null, false, true, 'BUTTON', true, true, 'system:SysDept:export', '', ''),
       (16, '部门管理-修改', 5, 2, '', null, null, false, true, 'BUTTON', true, true, 'system:SysDept:save', '', ''),
       (17, '部门管理-导入', 5, 4, '', null, null, false, true, 'BUTTON', true, true, 'system:SysDept:import', '', ''),
       (18, '部门管理-删除', 5, 3, '', null, null, false, true, 'BUTTON', true, true, 'system:SysDept:delete', '', ''),
       (19, '部门管理-新增', 5, 1, '', null, null, false, true, 'BUTTON', true, true, 'system:SysDept:save', '', ''),
       (20, '菜单管理-删除', 6, 3, '', null, null, false, true, 'BUTTON', true, true, 'system:SysMenu:delete', '', ''),
       (21, '菜单管理-导出', 6, 5, '', null, null, false, true, 'BUTTON', true, true, 'system:SysMenu:export', '', ''),
       (22, '菜单管理-新增', 6, 1, '', null, null, false, true, 'BUTTON', true, true, 'system:SysMenu:save', '', ''),
       (23, '菜单管理-导入', 6, 4, '', null, null, false, true, 'BUTTON', true, true, 'system:SysMenu:import', '', ''),
       (24, '菜单管理-修改', 6, 2, '', null, null, false, true, 'BUTTON', true, true, 'system:SysMenu:save', '', ''),
       (25, '角色管理-导入', 7, 4, '', null, null, false, true, 'BUTTON', true, true, 'system:SysRole:import', '', ''),
       (26, '角色管理-删除', 7, 3, '', null, null, false, true, 'BUTTON', true, true, 'system:SysRole:delete', '', ''),
       (27, '角色管理-修改', 7, 2, '', null, null, false, true, 'BUTTON', true, true, 'system:SysRole:save', '', ''),
       (28, '角色管理-新增', 7, 1, '', null, null, false, true, 'BUTTON', true, true, 'system:SysRole:save', '', ''),
       (29, '角色管理-导出', 7, 5, '', null, null, false, true, 'BUTTON', true, true, 'system:SysRole:export', '', ''),
       (30, '用户管理-修改', 8, 2, '', null, null, false, true, 'BUTTON', true, true, 'system:SysUser:save', '', ''),
       (31, '用户管理-导入', 8, 4, '', null, null, false, true, 'BUTTON', true, true, 'system:SysUser:import', '', ''),
       (32, '用户管理-新增', 8, 1, '', null, null, false, true, 'BUTTON', true, true, 'system:SysUser:save', '', ''),
       (33, '用户管理-删除', 8, 3, '', null, null, false, true, 'BUTTON', true, true, 'system:SysUser:delete', '', ''),
       (34, '用户管理-导出', 8, 5, '', null, null, false, true, 'BUTTON', true, true, 'system:SysUser:export', '', ''),
       (35, '代码生成', 2, 2, 'gen', '/gen/index', null, false, true, 'MENU', true, true, 'tool:gen:list', 'Menu', ''),
       (36, '修改生成配置', 2, 2, 'gen-edit/index/:tableId', '/gen/EditTable', null, false, false, 'MENU', false, true, 'tool:gen:edit', 'Menu', '/tool/gen'),
       (37, '测试菜单外链', 3, 1, 'https://www.baidu.com/', null, null, true, true, 'MENU', true, true, null, 'Menu', ''),
       (38, '测试目录外链', 3, 2, 'https://www.zhihu.com/', null, null, true, true, 'DIRECTORY', true, true, null, 'Menu', '');

INSERT INTO SYS_CONFIG (CONFIG_NAME, CONFIG_KEY, CONFIG_VALUE)
VALUES ('CONFIG_NAME1', 'CONFIG_KEY1', 'CONFIG_VALUE1'),
       ('CONFIG_NAME2', 'CONFIG_KEY2', 'CONFIG_VALUE2'),
       ('CONFIG_NAME3', 'CONFIG_KEY3', 'CONFIG_VALUE3'),
       ('CONFIG_NAME4', 'CONFIG_KEY4', 'CONFIG_VALUE4'),
       ('CONFIG_NAME5', 'CONFIG_KEY5', 'CONFIG_VALUE5'),
       ('CONFIG_NAME6', 'CONFIG_KEY6', 'CONFIG_VALUE6'),
       ('CONFIG_NAME7', 'CONFIG_KEY7', 'CONFIG_VALUE7'),
       ('CONFIG_NAME8', 'CONFIG_KEY8', 'CONFIG_VALUE8'),
       ('CONFIG_NAME9', 'CONFIG_KEY9', 'CONFIG_VALUE9'),
       ('CONFIG_NAME10', 'CONFIG_KEY10', 'CONFIG_VALUE10'),
       ('CONFIG_NAME11', 'CONFIG_KEY11', 'CONFIG_VALUE11'),
       ('CONFIG_NAME12', 'CONFIG_KEY12', 'CONFIG_VALUE12'),
       ('CONFIG_NAME13', 'CONFIG_KEY13', 'CONFIG_VALUE13'),
       ('CONFIG_NAME14', 'CONFIG_KEY14', 'CONFIG_VALUE14'),
       ('CONFIG_NAME15', 'CONFIG_KEY15', 'CONFIG_VALUE15'),
       ('CONFIG_NAME16', 'CONFIG_KEY16', 'CONFIG_VALUE16'),
       ('CONFIG_NAME17', 'CONFIG_KEY17', 'CONFIG_VALUE17'),
       ('CONFIG_NAME18', 'CONFIG_KEY18', 'CONFIG_VALUE18'),
       ('CONFIG_NAME19', 'CONFIG_KEY19', 'CONFIG_VALUE19');
