export interface SysMenu extends BaseEntity {
  // 主键
  id: number
  // 子列表
  children: Array<SysMenu>
  // 菜单名称
  menuName: string
  // 子列表
  children: Array<SysMenu>
  // 父菜单id
  parentId: number
  // 子列表
  children: Array<SysMenu>
  // 显示顺序
  sort: number
  // 子列表
  children: Array<SysMenu>
  // 路由地址
  path: string
  // 子列表
  children: Array<SysMenu>
  // 组件路径
  component: string
  // 子列表
  children: Array<SysMenu>
  // 路由参数
  queryParam: string
  // 子列表
  children: Array<SysMenu>
  // 是否为外链
  foreignLink: boolean
  // 子列表
  children: Array<SysMenu>
  // 是否缓存
  cached: boolean
  // 子列表
  children: Array<SysMenu>
  // 菜单类型
  menuType: string
  // 子列表
  children: Array<SysMenu>
  // 显示
  visible: boolean
  // 子列表
  children: Array<SysMenu>
  // 启用
  enabled: boolean
  // 子列表
  children: Array<SysMenu>
  // 权限标识
  perms: string
  // 子列表
  children: Array<SysMenu>
  // 菜单图标
  icon: string
  // 子列表
  children: Array<SysMenu>
}

export interface SysMenuQuery {
  // 菜单名称
  menuName?: string
  // 路由地址
  path?: string
  // 组件路径
  component?: string
}

export interface SysMenuForm {
  // 主键
  id?: number
  // 菜单名称
  menuName?: string
  // 父菜单id
  parentId?: number
  // 显示顺序
  sort?: number
  // 路由地址
  path?: string
  // 组件路径
  component?: string
  // 路由参数
  queryParam?: string
  // 是否为外链
  foreignLink?: boolean
  // 是否缓存
  cached?: boolean
  // 菜单类型
  menuType?: string
  // 显示
  visible?: boolean
  // 启用
  enabled?: boolean
  // 权限标识
  perms?: string
  // 菜单图标
  icon?: string
}
