/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/error/401': RouteRecordInfo<
      '/error/401',
      '/error/401',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/error/404': RouteRecordInfo<
      '/error/404',
      '/error/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/gen/': RouteRecordInfo<
      '/gen/',
      '/gen',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Index': RouteRecordInfo<
      '/Index',
      '/Index',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Login': RouteRecordInfo<
      '/Login',
      '/Login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/SysConfig': RouteRecordInfo<
      '/system/SysConfig',
      '/system/SysConfig',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/SysDept': RouteRecordInfo<
      '/system/SysDept',
      '/system/SysDept',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/SysMenu': RouteRecordInfo<
      '/system/SysMenu',
      '/system/SysMenu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/SysRole': RouteRecordInfo<
      '/system/SysRole',
      '/system/SysRole',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/SysUser': RouteRecordInfo<
      '/system/SysUser',
      '/system/SysUser',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Test': RouteRecordInfo<
      '/Test',
      '/Test',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/views/error/401.vue': {
      routes:
        | '/error/401'
      views:
        | never
    }
    'src/views/error/404.vue': {
      routes:
        | '/error/404'
      views:
        | never
    }
    'src/views/gen/index.vue': {
      routes:
        | '/gen/'
      views:
        | never
    }
    'src/views/Index.vue': {
      routes:
        | '/Index'
      views:
        | never
    }
    'src/views/Login.vue': {
      routes:
        | '/Login'
      views:
        | never
    }
    'src/views/system/SysConfig.vue': {
      routes:
        | '/system/SysConfig'
      views:
        | never
    }
    'src/views/system/SysDept.vue': {
      routes:
        | '/system/SysDept'
      views:
        | never
    }
    'src/views/system/SysMenu.vue': {
      routes:
        | '/system/SysMenu'
      views:
        | never
    }
    'src/views/system/SysRole.vue': {
      routes:
        | '/system/SysRole'
      views:
        | never
    }
    'src/views/system/SysUser.vue': {
      routes:
        | '/system/SysUser'
      views:
        | never
    }
    'src/views/Test.vue': {
      routes:
        | '/Test'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
