/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/(default)': RouteRecordInfo<
      '/(default)',
      '/',
      Record<never, never>,
      Record<never, never>,
      | '/(default)/gen/gen'
      | '/(default)/system/sysDept'
      | '/(default)/system/sysUser'
    >,
    '/(default)/gen/gen': RouteRecordInfo<
      '/(default)/gen/gen',
      '/gen/gen',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(default)/system/sysDept': RouteRecordInfo<
      '/(default)/system/sysDept',
      '/system/sysDept',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(default)/system/sysUser': RouteRecordInfo<
      '/(default)/system/sysUser',
      '/system/sysUser',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/401': RouteRecordInfo<
      '/401',
      '/401',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(default).vue': {
      routes:
        | '/(default)'
        | '/(default)/gen/gen'
        | '/(default)/system/sysDept'
        | '/(default)/system/sysUser'
      views:
        | 'default'
    }
    'src/pages/(default)/gen/gen.vue': {
      routes:
        | '/(default)/gen/gen'
      views:
        | never
    }
    'src/pages/(default)/system/sysDept.vue': {
      routes:
        | '/(default)/system/sysDept'
      views:
        | never
    }
    'src/pages/(default)/system/sysUser.vue': {
      routes:
        | '/(default)/system/sysUser'
      views:
        | never
    }
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'src/pages/401.vue': {
      routes:
        | '/401'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
